
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem verdi-sequencer)
    (:domain verdi-catalog)

    (:objects
        a b data-mapper error_handler fallback slot-filler slot_filler_for_planner slot_filler_form_agent - agent
        data_objects - type__of__data_objects
        job_id - type__of__job_id
        list_of_signature_item_spec - type__of__list_of_signature_item_spec
        occupation_id - type__of__occupation_id
        original_error - type__of__original_error
        sf_context - type__of__sf_context
        slot_fill_form_title - type__of__slot_fill_form_title
    )

    (:init
        (= (affinity job_id occupation_id) 5.0)
        (= (total-cost) 0.0)
        (is_mappable job_id occupation_id)
        (is_slotfillable sf_context)
        (is_slotfillable data_objects)
        (is_slotfillable slot_fill_form_title)
        (is_slotfillable job_id)
        (is_slotfillable list_of_signature_item_spec)
        (is_slotfillable original_error)
        (is_slotfillable occupation_id)
    )

    (:goal
        (has_done b)
    )

    (:metric minimize
        (total-cost)
    )
)